const freelances = [
  {
    id: "1",
    name: "Pabi Diédhiou",
    job: "Chef de Projet",
    picture: "http://127.0.0.1:7000/images/1.jpeg",
    skills: ["React Native"],
    location: "Dakar",
    available: true,
    tjm: 500,
  },
  {
    id: "2",
    name: "Awa Diouf",
    job: "Développeuse fullstack",
    picture: "http://localhost:7000/images/2.jpeg",
    skills: ["Node JS", "Vue.js", "React", "AWS"],
    location: "Dakar",
    available: false,
    tjm: 620,
  },
  {
    id: "3",
    name: "Soda Ndiaye",
    job: "Développeuse frontend",
    picture: "http://localhost:7000/images/3.jpeg",
    skills: ["React", "Gatsby", "Next.js"],
    location: "Bordeaux",
    available: true,
    tjm: 520,
  },
  {
    id: "4",
    name: "Daouda Ndiaye",
    job: "Product Designer",
    picture: "http://localhost:7000/images/4.jpeg",
    skills: ["Figma", "Webflow"],
    location: "Bambey",
    available: false,
    tjm: 650,
  },
  {
    id: "5",
    name: "Ly Baba",
    job: "Développeur mobile",
    picture: "http://localhost:7000/images/5.jpeg",
    skills: ["IOS", "Android"],
    location: "France",
    available: false,
    tjm: 450,
  },
  {
    id: "6",
    name: "Pape Abdoulaye Faye",
    job: "Développeur backend",
    picture: "http://localhost:7000/images/6.jpeg",
    skills: ["Python", "Django", "Docker"],
    location: "Dakar",
    available: true,
    tjm: 510,
  },
  {
    id: "7",
    name: "Mountaga Ba",
    job: "Designer",
    picture: "http://localhost:7000/images/7.jpeg",
    skills: ["Sketch", "Illustrator"],
    location: "Marsassoum",
    available: true,
    tjm: 480,
  },
  {
    id: "8",
    name: "Pape Maguette Seye",
    job: "Développeur frontend",
    picture: "http://localhost:7000/images/8.jpeg",
    skills: ["SEO", "Javascript Vanilla"],
    location: "France",
    available: false,
    tjm: 560,
  },
];

module.exports = freelances;
